### ISSUE TITLE
Heatshrink incompatibility

### ISSUE THREAD

**Issue by ckrenslehner** [wagnerf42/gps#1]
Due to an issue in the crate, your crate relies on, this crate is most likely incompatible with the original implementation of heatshrink (https://github.com/atomicobject/heatshrink).

See https://github.com/snakehand/heatshrink/issues/1

Greetings, Christian

**Comment by wagnerf42** [comment]
hey, thanks a lot for the information (and for detecting the problem). i had no issues myself but i'll do the upgrade for sure.

**Comment by ckrenslehner** [comment]
You are welcome :-)
